[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="failedTests" type="java.util.SortedMap<org.testng.IClass, java.util.List<org.testng.ITestResult>>" --]
[#-- @ftlvariable name="skippedTests" type="java.util.SortedMap<org.testng.IClass, java.util.List<org.testng.ITestResult>>" --]
[#-- @ftlvariable name="passedTests" type="java.util.SortedMap<org.testng.IClass, java.util.List<org.testng.ITestResult>>" --]
[#-- @ftlvariable name="failedConfigurations" type="java.util.SortedMap<org.testng.IClass, java.util.List<org.testng.ITestResult>>" --]
[#-- @ftlvariable name="skippedConfigurations" type="java.util.SortedMap<org.testng.IClass, java.util.List<org.testng.ITestResult>>" --]
[#-- @ftlvariable name="result" type="org.testng.ISuiteResult" --]
[#-- @ftlvariable name="onlyReportFailures" type="boolean" --]
[#-- @ftlvariable name="suites" type="java.util.Collection<org.testng.ISuite>" --]
[#-- @ftlvariable name="groups" type="java.util.SortedMap<String, java.util.SortedSet<org.testng.ITestNGMethod>>" --]
[#-- @ftlvariable name="suite" type="org.testng.ISuite" --]
[#-- @ftlvariable name="meta" type="org.uncommons.reportng.ReportMetadata" --]
[#-- @ftlvariable name="messages" type="java.util.ResourceBundle" --]
[#-- @ftlvariable name="utils" type="org.uncommons.reportng.ReportNGUtils" --]
